services:
  backend:
    build: ./backend

    ports:
      - "8000:8000"

    restart: always
  
  backend2:
    build: ./backend2

    ports:
      - "9000:9000"

    restart: always

  frontend:
    build: ./frontend

    ports:
      - "8080:80"

    depends_on:
      - backend

    restart: always
