# Generated by Django 6.0.6 on 2026-07-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capsule', models.CharField(max_length=30, verbose_name='胶囊')),
                ('specification', models.CharField(max_length=100, verbose_name='规格')),
                ('clamp', models.CharField(max_length=30, verbose_name='夹盘')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5, verbose_name='类型')),
                ('specification', models.CharField(max_length=30, unique=True, verbose_name='规格')),
                ('stock_no', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
