# Generated by Django 6.0.6 on 2026-07-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capsule', models.CharField(max_length=30, verbose_name='胶囊')),
                ('clamp', models.CharField(max_length=30, verbose_name='夹盘')),
                ('specification', models.CharField(blank=True, default='', max_length=100, verbose_name='规格')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='优先级')),
                ('backup1', models.CharField(blank=True, max_length=100, verbose_name='备用1')),
                ('backup2', models.CharField(blank=True, max_length=100, verbose_name='备用2')),
                ('backup3', models.CharField(blank=True, max_length=100, verbose_name='备用3')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineStyle', models.CharField(default='', max_length=10, verbose_name='机型')),
                ('Clamp', models.CharField(default='', max_length=10, verbose_name='夹盘')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='库存数')),
                ('backup1', models.PositiveIntegerField(default=0, verbose_name='备用1')),
                ('backup2', models.PositiveIntegerField(default=0, verbose_name='备用2')),
                ('backup3', models.PositiveIntegerField(default=0, verbose_name='备用3')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
