# Generated by Django 6.0.6 on 2026-07-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_mes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineStyle', models.CharField(default='', max_length=10, verbose_name='机型')),
                ('MachineID', models.CharField(default='', max_length=10, verbose_name='夹盘')),
                ('factory', models.PositiveIntegerField(default=0, verbose_name='库存数')),
                ('backup1', models.PositiveIntegerField(default=0, verbose_name='备用1')),
                ('backup2', models.PositiveIntegerField(default=0, verbose_name='备用2')),
                ('backup3', models.PositiveIntegerField(default=0, verbose_name='备用3')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
