# Generated by Django 6.0.6 on 2026-07-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_mes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_no',
            new_name='quantity',
        ),
    ]
