# Generated by Django 6.0.6 on 2026-07-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_mes', '0002_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='backup1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备用1'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='backup2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备用2'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='backup3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备用3'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='backup1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='备用1'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='backup2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='备用2'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='backup3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='备用3'),
        ),
    ]
